number1=float(input("Enter number1 : "))
number2=float(input("Enter number2 : "))

print("Number1 = ",number1," Number2 = ",number2)
print(number1," + ",number2," = ",(number1+number2))
print(number1," - ",number2," = ",(number1-number2))
print(number1," / ",number2," = ",(number1/number2))
print(number1," // ",number2," = ",(number1//number2))
print(number1," * ",number2," = ",(number1*number2))
print(number1," ** ",number2," = ",(number1**number2))
print(number1," % ",number2," = ",(number1%number2))
